import type { Metadata } from "next";
import 'bootstrap/dist/css/bootstrap.min.css'
import "@splidejs/splide/dist/css/splide.min.css";
import "material-icons/iconfont/material-icons.css";
import "./globals.css";
import Navbar from "./components/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        
        {children}
      </body>
    </html>
  );
}
