import type { Metadata } from "next";
import 'bootstrap/dist/css/bootstrap.min.css'
import "@splidejs/splide/dist/css/splide.min.css";
import "material-icons/iconfont/material-icons.css";
import "./globals.css";
import Navbar from "./components/Navbar";
import RightClickWarning from "./components/RightClickWarning";


export const metadata: Metadata = {
  title: "Dicky Dns",
  description: "Generated by create next app",
  icons: {
    icon: "/images/logo.png",
    shortcut: "/images/logo.png",
    apple: "/images/logo.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {/* <RightClickWarning /> */}
        
        {children}
      </body>
    </html>
  );
}
